-- Create table for THT Assessment
CREATE TABLE IF NOT EXISTS `penilaian_medis_ralan_tht` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `kd_dokter` varchar(20) DEFAULT NULL,
  `anamnesis` varchar(50) DEFAULT NULL,
  `hubungan` varchar(50) DEFAULT NULL,
  `keluhan_utama` text DEFAULT NULL,
  `rps` text DEFAULT NULL,
  `rpd` text DEFAULT NULL,
  `rpo` text DEFAULT NULL,
  `alergi` varchar(255) DEFAULT NULL,
  `kesadaran` varchar(50) DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `td` varchar(20) DEFAULT NULL,
  `nadi` varchar(10) DEFAULT NULL,
  `suhu` varchar(10) DEFAULT NULL,
  `rr` varchar(10) DEFAULT NULL,
  `bb` varchar(10) DEFAULT NULL,
  `nyeri` varchar(10) DEFAULT NULL,
  `gcs` varchar(20) DEFAULT NULL,
  `kepala` varchar(50) DEFAULT NULL,
  `thoraks` varchar(50) DEFAULT NULL,
  `abdomen` varchar(50) DEFAULT NULL,
  `ekstremitas` varchar(50) DEFAULT NULL,
  `genetalia` varchar(50) DEFAULT NULL,
  `columna` varchar(50) DEFAULT NULL,
  `muskulos` varchar(50) DEFAULT NULL,
  `lainnya` text DEFAULT NULL,
  `ket_lokalis` text DEFAULT NULL,
  `lab` text DEFAULT NULL,
  `rad` text DEFAULT NULL,
  `pemeriksaan` text DEFAULT NULL,
  `diagnosis` text DEFAULT NULL,
  `diagnosis2` text DEFAULT NULL,
  `permasalahan` text DEFAULT NULL,
  `terapi` text DEFAULT NULL,
  `tindakan` text DEFAULT NULL,
  `edukasi` text DEFAULT NULL,
  PRIMARY KEY (`no_rawat`,`tanggal`),
  KEY `kd_dokter` (`kd_dokter`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
